apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          echo "<h1>Pod Information</h1>" > /usr/share/nginx/html/index.html;
          echo "<p>Pod Name: $POD_NAME</p>" >> /usr/share/nginx/html/index.html;
          echo "<p>Node: $NODE_NAME</p>" >> /usr/share/nginx/html/index.html;
          echo "<p>Namespace: $POD_NAMESPACE</p>" >> /usr/share/nginx/html/index.html;
          echo "<p>Pod IP: $POD_IP</p>" >> /usr/share/nginx/html/index.html;
          nginx -g 'daemon off;'

